# Docker Compose for production deployment
version: '3.8'

services:
  backend:
    build:
      target: production
    environment:
      NODE_ENV: production
      LOG_LEVEL: warn
    restart: always
    # Remove development volumes
    volumes:
      - uploads_data:/app/uploads
    # Use production command
    command: ["dumb-init", "node", "dist/main"]

  db:
    # Don't expose database port in production
    ports: []
    environment:
      # Remove trust auth method in production
      POSTGRES_HOST_AUTH_METHOD: md5

  # Remove pgAdmin in production
  pgadmin:
    profiles:
      - debug

  # Add Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: education_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - education-network